quarkus.oidc.auth-server-url=https://localhost:8180/realms/quarkus-mtls
quarkus.oidc.client-id=quarkus
quarkus.oidc.application-type=web-app

quarkus.oidc.tls.tls-configuration-name=oidc
quarkus.tls.oidc.key-store.p12.path=certs/quarkus-keystore.p12
quarkus.tls.oidc.key-store.p12.password=changeit

quarkus.oidc.token-state-manager.encryption-secret=eUk1p7UB3nFiXZGUXi0uph1Y9p34YhBU

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
